config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :students
  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    def index
     @students=Student.all
    end

    def new
     @student=Student.new

    end 
    
    def create 
        @student=Student.new(student_params)
        if @student.save 
            flash[:notice]="student created successfully"
            redirect_to students_path
        else
            flash[:alert] = "There was an error creating the student."
            render :new
        end
    end


    def edit
    @student = Student.find(params[:id])
    end

    def update
        @student = Student.find(params[:id])
        if @student.update(student_params)
            flash[:notice]='student updated successfully'
            redirect_to students_path
        else 
         flash[:notice]='something wrong'
         render :edit
        end
    end
    def destroy
        @student = Student.find(params[:id]) 
        if @student.destroy
            flash[:notice]= 'student remove successfully'
        else 
            flash[:notice]= 'something  wrong'
        end
    end
    private
    def student_params
        params.require(:student).permit(:firstname, :lastname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentManagment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>

  <body>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with model: @student do |f| %>
    <div>
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
    <br>
    </div>
    <div>
    <%= f.label :lastname %>
    <%= f.text_field :lastname%>
    <br>
    </div>
    <div>
    <%= f.label :email %>
    <%= f.text_field :email%>
    <br>
    </div>
    <div>
    <%= f.submit  %>
    </div>
<% end %>

app/views/students/edit.html.erb
<h1> edit students detail </h1>
<%= render 'form' %>

app/views/students/index.html.erb
<h1>Listing of All Students</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>links</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.firstname %></td>
        <td><%= student.lastname %></td>
        <td><%= student.email %></td>
        <td><span style="padding-right: 10px;"><%= link_to 'Add students', new_student_path %></span></td>
        <td><span style="padding-right: 10px;"><%= link_to 'Edit student', edit_student_path(student) %></span></td>
        <td><%= button_to 'Destroy', student_path(student), method: :delete %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1> Add new student </h1>
<%= render 'form' %>